services:
  database:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  application:
    image: alpine:latest
    working_dir: /var/www/application
    volumes:
      - ./:/var/www/application
    env_file: .env
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - backend
    entrypoint: ./app

volumes:
  data:
networks:
  backend: