base:
  pattern: "/"
  function: "BaseHandler"

login_page:
  pattern: "/login"
  function: "LoginPage"

login_connection:
  pattern: "/loginConnection"
  function: "LoginConnection"
  methods: ["POST"]
  redirect: "/login"

login_list:
  pattern: "/loginList"
  function: "LoginListPage"

register_page:
  pattern: "/register"
  function: "RegisterPage"

register_new_account:
  pattern: "/createAccount"
  function: "RegisterNewAccount"
  methods: ["POST"]
  redirect: "/register"